version: '3.3'

services:
  db:
    image: mysql:8.0.32
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Apple#123
      MYSQL_DATABASE: weatherapp
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pApple#123"]
      interval: 10s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
    container_name: node-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Apple#123
      DB_NAME: weatherapp
      JWT_SECRET: supersecretjwt
    depends_on:
      - db

volumes:
  db_data:
